"""initial_schema

Revision ID: 366ba6a32c1d
Revises: 
Create Date: 2026-03-30 02:12:53.006011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366ba6a32c1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment='e.g. plan_version, reservation, transfer, snapshot'),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='e.g. created, approved, rejected, overridden, arrived'),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('dcs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_dcs_code', 'dcs', ['code'], unique=False)
    op.create_index('ix_dcs_region', 'dcs', ['region'], unique=False)
    op.create_table('demo_arrival_events',
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='vessel_arrival or lorry_arrival'),
    sa.Column('reference_id', sa.Integer(), nullable=False, comment='manifest_snapshot_id for vessel, demo_transfer_id for lorry'),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demo_arrival_time', 'demo_arrival_events', ['event_time'], unique=False)
    op.create_index('ix_demo_arrival_type', 'demo_arrival_events', ['event_type'], unique=False)
    op.create_table('engine_runs',
    sa.Column('engine_type', sa.String(length=10), nullable=False, comment='m1, m2, or m3'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='running, completed, failed'),
    sa.Column('input_snapshot_ids', sa.JSON(), nullable=True, comment='JSON map of snapshot type -> snapshot id used as input'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_engine_run_started', 'engine_runs', ['started_at'], unique=False)
    op.create_index('ix_engine_run_status', 'engine_runs', ['status'], unique=False)
    op.create_index('ix_engine_run_type', 'engine_runs', ['engine_type'], unique=False)
    op.create_table('lorries',
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('lorry_type', sa.String(length=20), nullable=False, comment='normal or reefer'),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='available or unavailable'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_index('ix_lorries_lorry_type', 'lorries', ['lorry_type'], unique=False)
    op.create_index('ix_lorries_registration', 'lorries', ['registration'], unique=False)
    op.create_index('ix_lorries_status', 'lorries', ['status'], unique=False)
    op.create_table('lorry_state_snapshots',
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lorry_state_snap_time', 'lorry_state_snapshots', ['snapshot_time'], unique=False)
    op.create_table('route_edges',
    sa.Column('origin_type', sa.String(length=20), nullable=False, comment='warehouse or dc'),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_type', sa.String(length=20), nullable=False, comment='dc'),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('travel_time_hours', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_route_destination', 'route_edges', ['destination_type', 'destination_id'], unique=False)
    op.create_index('ix_route_origin', 'route_edges', ['origin_type', 'origin_id'], unique=False)
    op.create_table('skus',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('reefer_required', sa.Boolean(), nullable=False),
    sa.Column('unit_weight_kg', sa.Float(), nullable=False),
    sa.Column('unit_volume_m3', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_skus_category', 'skus', ['category'], unique=False)
    op.create_index('ix_skus_code', 'skus', ['code'], unique=False)
    op.create_table('vessels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_vessels_code', 'vessels', ['code'], unique=False)
    op.create_table('warehouse_stock_snapshots',
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wh_stock_snap_time', 'warehouse_stock_snapshots', ['snapshot_time'], unique=False)
    op.create_table('dc_stock_snapshots',
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dc_id'], ['dcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dc_stock_snap_dc', 'dc_stock_snapshots', ['dc_id'], unique=False)
    op.create_index('ix_dc_stock_snap_time', 'dc_stock_snapshots', ['snapshot_time'], unique=False)
    op.create_table('demo_stock_projections',
    sa.Column('location_type', sa.String(length=20), nullable=False, comment='warehouse or dc'),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('projected_quantity', sa.Integer(), nullable=False),
    sa.Column('projection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demo_proj_location', 'demo_stock_projections', ['location_type', 'location_id'], unique=False)
    op.create_index('ix_demo_proj_sku', 'demo_stock_projections', ['sku_id'], unique=False)
    op.create_index('ix_demo_proj_time', 'demo_stock_projections', ['projection_time'], unique=False)
    op.create_table('eta_snapshots',
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('eta_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eta_fetched', 'eta_snapshots', ['fetched_at'], unique=False)
    op.create_index('ix_eta_vessel', 'eta_snapshots', ['vessel_id'], unique=False)
    op.create_table('lorry_state_items',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('lorry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='available or unavailable'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lorry_id'], ['lorries.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['lorry_state_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lorry_state_item_lorry', 'lorry_state_items', ['lorry_id'], unique=False)
    op.create_index('ix_lorry_state_item_snap', 'lorry_state_items', ['snapshot_id'], unique=False)
    op.create_table('m2_requests',
    sa.Column('engine_run_id', sa.Integer(), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False, comment='critical, high, medium, low'),
    sa.Column('required_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dc_id'], ['dcs.id'], ),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_m2_req_dc', 'm2_requests', ['dc_id'], unique=False)
    op.create_index('ix_m2_req_run', 'm2_requests', ['engine_run_id'], unique=False)
    op.create_index('ix_m2_req_sku', 'm2_requests', ['sku_id'], unique=False)
    op.create_index('ix_m2_req_urgency', 'm2_requests', ['urgency'], unique=False)
    op.create_table('m3_plan_versions',
    sa.Column('engine_run_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.String(length=20), nullable=False, comment='draft, approved, rejected'),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_m3_plan_is_best', 'm3_plan_versions', ['is_best'], unique=False)
    op.create_index('ix_m3_plan_run', 'm3_plan_versions', ['engine_run_id'], unique=False)
    op.create_index('ix_m3_plan_status', 'm3_plan_versions', ['plan_status'], unique=False)
    op.create_table('manifest_snapshots',
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='active, arrived, cancelled'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manifest_snap_status', 'manifest_snapshots', ['status'], unique=False)
    op.create_index('ix_manifest_snap_time', 'manifest_snapshots', ['snapshot_time'], unique=False)
    op.create_index('ix_manifest_snap_vessel', 'manifest_snapshots', ['vessel_id'], unique=False)
    op.create_table('sales_history_records',
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dc_id'], ['dcs.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_date', 'sales_history_records', ['sale_date'], unique=False)
    op.create_index('ix_sales_dc', 'sales_history_records', ['dc_id'], unique=False)
    op.create_index('ix_sales_dc_sku_date', 'sales_history_records', ['dc_id', 'sku_id', 'sale_date'], unique=False)
    op.create_index('ix_sales_sku', 'sales_history_records', ['sku_id'], unique=False)
    op.create_table('warehouse_stock_items',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('effective_quantity', sa.Integer(), nullable=False, comment='physical - reserved'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['warehouse_stock_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wh_stock_item_sku', 'warehouse_stock_items', ['sku_id'], unique=False)
    op.create_index('ix_wh_stock_item_snap', 'warehouse_stock_items', ['snapshot_id'], unique=False)
    op.create_table('dc_stock_items',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('in_transit_quantity', sa.Integer(), nullable=False),
    sa.Column('effective_quantity', sa.Integer(), nullable=False, comment='physical + in_transit'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dc_stock_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dc_stock_item_sku', 'dc_stock_items', ['sku_id'], unique=False)
    op.create_index('ix_dc_stock_item_snap', 'dc_stock_items', ['snapshot_id'], unique=False)
    op.create_table('demo_reservations',
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active or released'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_version_id'], ['m3_plan_versions.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demo_res_plan', 'demo_reservations', ['plan_version_id'], unique=False)
    op.create_index('ix_demo_res_sku', 'demo_reservations', ['sku_id'], unique=False)
    op.create_index('ix_demo_res_status', 'demo_reservations', ['status'], unique=False)
    op.create_table('demo_transfers',
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('lorry_id', sa.Integer(), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, in_transit, arrived'),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dc_id'], ['dcs.id'], ),
    sa.ForeignKeyConstraint(['lorry_id'], ['lorries.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['m3_plan_versions.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demo_xfer_dc', 'demo_transfers', ['dc_id'], unique=False)
    op.create_index('ix_demo_xfer_lorry', 'demo_transfers', ['lorry_id'], unique=False)
    op.create_index('ix_demo_xfer_plan', 'demo_transfers', ['plan_version_id'], unique=False)
    op.create_index('ix_demo_xfer_sku', 'demo_transfers', ['sku_id'], unique=False)
    op.create_index('ix_demo_xfer_status', 'demo_transfers', ['status'], unique=False)
    op.create_table('m3_plan_stops',
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('lorry_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time_est', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dc_id'], ['dcs.id'], ),
    sa.ForeignKeyConstraint(['lorry_id'], ['lorries.id'], ),
    sa.ForeignKeyConstraint(['plan_version_id'], ['m3_plan_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_m3_stop_dc', 'm3_plan_stops', ['dc_id'], unique=False)
    op.create_index('ix_m3_stop_lorry', 'm3_plan_stops', ['lorry_id'], unique=False)
    op.create_index('ix_m3_stop_plan', 'm3_plan_stops', ['plan_version_id'], unique=False)
    op.create_table('manifest_lines',
    sa.Column('manifest_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reefer_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manifest_snapshot_id'], ['manifest_snapshots.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manifest_line_sku', 'manifest_lines', ['sku_id'], unique=False)
    op.create_index('ix_manifest_line_snap', 'manifest_lines', ['manifest_snapshot_id'], unique=False)
    op.create_table('planner_decisions',
    sa.Column('plan_version_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sa.String(length=20), nullable=False, comment='approve, reject, override'),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_version_id'], ['m3_plan_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planner_dec_plan', 'planner_decisions', ['plan_version_id'], unique=False)
    op.create_index('ix_planner_dec_time', 'planner_decisions', ['decided_at'], unique=False)
    op.create_index('ix_planner_dec_type', 'planner_decisions', ['decision_type'], unique=False)
    op.create_table('m1_results',
    sa.Column('engine_run_id', sa.Integer(), nullable=False),
    sa.Column('manifest_line_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_band', sa.String(length=20), nullable=False, comment='critical, high, medium, low'),
    sa.Column('reefer_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ),
    sa.ForeignKeyConstraint(['manifest_line_id'], ['manifest_lines.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_m1_result_band', 'm1_results', ['priority_band'], unique=False)
    op.create_index('ix_m1_result_run', 'm1_results', ['engine_run_id'], unique=False)
    op.create_index('ix_m1_result_sku', 'm1_results', ['sku_id'], unique=False)
    op.create_table('m3_plan_items',
    sa.Column('plan_stop_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_stop_id'], ['m3_plan_stops.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_m3_item_sku', 'm3_plan_items', ['sku_id'], unique=False)
    op.create_index('ix_m3_item_stop', 'm3_plan_items', ['plan_stop_id'], unique=False)
    op.create_table('override_reasons',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=False),
    sa.Column('new_value', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['planner_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_override_decision', 'override_reasons', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_override_decision', table_name='override_reasons')
    op.drop_table('override_reasons')
    op.drop_index('ix_m3_item_stop', table_name='m3_plan_items')
    op.drop_index('ix_m3_item_sku', table_name='m3_plan_items')
    op.drop_table('m3_plan_items')
    op.drop_index('ix_m1_result_sku', table_name='m1_results')
    op.drop_index('ix_m1_result_run', table_name='m1_results')
    op.drop_index('ix_m1_result_band', table_name='m1_results')
    op.drop_table('m1_results')
    op.drop_index('ix_planner_dec_type', table_name='planner_decisions')
    op.drop_index('ix_planner_dec_time', table_name='planner_decisions')
    op.drop_index('ix_planner_dec_plan', table_name='planner_decisions')
    op.drop_table('planner_decisions')
    op.drop_index('ix_manifest_line_snap', table_name='manifest_lines')
    op.drop_index('ix_manifest_line_sku', table_name='manifest_lines')
    op.drop_table('manifest_lines')
    op.drop_index('ix_m3_stop_plan', table_name='m3_plan_stops')
    op.drop_index('ix_m3_stop_lorry', table_name='m3_plan_stops')
    op.drop_index('ix_m3_stop_dc', table_name='m3_plan_stops')
    op.drop_table('m3_plan_stops')
    op.drop_index('ix_demo_xfer_status', table_name='demo_transfers')
    op.drop_index('ix_demo_xfer_sku', table_name='demo_transfers')
    op.drop_index('ix_demo_xfer_plan', table_name='demo_transfers')
    op.drop_index('ix_demo_xfer_lorry', table_name='demo_transfers')
    op.drop_index('ix_demo_xfer_dc', table_name='demo_transfers')
    op.drop_table('demo_transfers')
    op.drop_index('ix_demo_res_status', table_name='demo_reservations')
    op.drop_index('ix_demo_res_sku', table_name='demo_reservations')
    op.drop_index('ix_demo_res_plan', table_name='demo_reservations')
    op.drop_table('demo_reservations')
    op.drop_index('ix_dc_stock_item_snap', table_name='dc_stock_items')
    op.drop_index('ix_dc_stock_item_sku', table_name='dc_stock_items')
    op.drop_table('dc_stock_items')
    op.drop_index('ix_wh_stock_item_snap', table_name='warehouse_stock_items')
    op.drop_index('ix_wh_stock_item_sku', table_name='warehouse_stock_items')
    op.drop_table('warehouse_stock_items')
    op.drop_index('ix_sales_sku', table_name='sales_history_records')
    op.drop_index('ix_sales_dc_sku_date', table_name='sales_history_records')
    op.drop_index('ix_sales_dc', table_name='sales_history_records')
    op.drop_index('ix_sales_date', table_name='sales_history_records')
    op.drop_table('sales_history_records')
    op.drop_index('ix_manifest_snap_vessel', table_name='manifest_snapshots')
    op.drop_index('ix_manifest_snap_time', table_name='manifest_snapshots')
    op.drop_index('ix_manifest_snap_status', table_name='manifest_snapshots')
    op.drop_table('manifest_snapshots')
    op.drop_index('ix_m3_plan_status', table_name='m3_plan_versions')
    op.drop_index('ix_m3_plan_run', table_name='m3_plan_versions')
    op.drop_index('ix_m3_plan_is_best', table_name='m3_plan_versions')
    op.drop_table('m3_plan_versions')
    op.drop_index('ix_m2_req_urgency', table_name='m2_requests')
    op.drop_index('ix_m2_req_sku', table_name='m2_requests')
    op.drop_index('ix_m2_req_run', table_name='m2_requests')
    op.drop_index('ix_m2_req_dc', table_name='m2_requests')
    op.drop_table('m2_requests')
    op.drop_index('ix_lorry_state_item_snap', table_name='lorry_state_items')
    op.drop_index('ix_lorry_state_item_lorry', table_name='lorry_state_items')
    op.drop_table('lorry_state_items')
    op.drop_index('ix_eta_vessel', table_name='eta_snapshots')
    op.drop_index('ix_eta_fetched', table_name='eta_snapshots')
    op.drop_table('eta_snapshots')
    op.drop_index('ix_demo_proj_time', table_name='demo_stock_projections')
    op.drop_index('ix_demo_proj_sku', table_name='demo_stock_projections')
    op.drop_index('ix_demo_proj_location', table_name='demo_stock_projections')
    op.drop_table('demo_stock_projections')
    op.drop_index('ix_dc_stock_snap_time', table_name='dc_stock_snapshots')
    op.drop_index('ix_dc_stock_snap_dc', table_name='dc_stock_snapshots')
    op.drop_table('dc_stock_snapshots')
    op.drop_index('ix_wh_stock_snap_time', table_name='warehouse_stock_snapshots')
    op.drop_table('warehouse_stock_snapshots')
    op.drop_index('ix_vessels_code', table_name='vessels')
    op.drop_table('vessels')
    op.drop_index('ix_skus_code', table_name='skus')
    op.drop_index('ix_skus_category', table_name='skus')
    op.drop_table('skus')
    op.drop_index('ix_route_origin', table_name='route_edges')
    op.drop_index('ix_route_destination', table_name='route_edges')
    op.drop_table('route_edges')
    op.drop_index('ix_lorry_state_snap_time', table_name='lorry_state_snapshots')
    op.drop_table('lorry_state_snapshots')
    op.drop_index('ix_lorries_status', table_name='lorries')
    op.drop_index('ix_lorries_registration', table_name='lorries')
    op.drop_index('ix_lorries_lorry_type', table_name='lorries')
    op.drop_table('lorries')
    op.drop_index('ix_engine_run_type', table_name='engine_runs')
    op.drop_index('ix_engine_run_status', table_name='engine_runs')
    op.drop_index('ix_engine_run_started', table_name='engine_runs')
    op.drop_table('engine_runs')
    op.drop_index('ix_demo_arrival_type', table_name='demo_arrival_events')
    op.drop_index('ix_demo_arrival_time', table_name='demo_arrival_events')
    op.drop_table('demo_arrival_events')
    op.drop_index('ix_dcs_region', table_name='dcs')
    op.drop_index('ix_dcs_code', table_name='dcs')
    op.drop_table('dcs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
